export default defineAppConfig({
  shell: {
    navigation: [
      {
        label: "公司总览",
        to: "/company",
        icon: "i-lucide-building-2",
        description: "团队、当前工作与本地运行边界",
      },
      {
        label: "收件箱",
        to: "/inbox",
        icon: "i-lucide-inbox",
        description: "需要你处理的决定、阻塞与交付",
      },
      {
        label: "工作",
        to: "/work",
        icon: "i-lucide-panels-top-left",
        description: "目标、执行过程与当前进展",
      },
      {
        label: "董事会",
        to: "/company/board",
        icon: "i-lucide-layout-dashboard",
        description: "董事会讨论、决策与人工接管",
      },
      {
        label: "运营日志",
        to: "/company/operations",
        icon: "i-lucide-list-tree",
        description: "公司运行记录、风险信号与交付轨迹",
      },
      {
        label: "团队",
        to: "/team",
        icon: "i-lucide-users-round",
        description: "团队责任、负载与工作证据",
      },
      {
        label: "成果库",
        to: "/library",
        icon: "i-lucide-library",
        description: "成果、报告与历史版本",
      },
      {
        label: "设置",
        to: "/settings",
        icon: "i-lucide-settings",
        description: "本地运行、模型服务与数据设置",
      },
    ],
  },
  experience: {
    statusLabels: {
      draft: "草稿",
      needs_input: "等待补充",
      ready: "可开始",
      running: "执行中",
      paused: "已暂停",
      blocked: "受阻",
      needs_approval: "等待审批",
      reviewing: "验收中",
      revision: "修订中",
      delivered: "待验收",
      accepted: "已验收",
      archived: "已归档",
      failed: "失败",
      cancelled: "已取消",
    },
    actionLabels: {
      continue_editing: "继续编辑",
      answer_question: "回答问题",
      start_work: "开始执行",
      adjust_brief: "调整目标摘要",
      view_progress: "查看进展",
      pause_work: "暂停",
      resume_work: "恢复",
      stop_work: "停止",
      resolve_blocker: "修复阻塞",
      approve: "批准",
      reject: "拒绝",
      request_change: "要求修改",
      view_evidence: "查看证据",
      view_revision: "查看修改范围",
      open_delivery: "查看交付",
      accept_delivery: "接受交付",
      retry: "重试",
      open_diagnostics: "查看诊断",
      view_retained_results: "查看保留成果",
      archive: "归档",
      restore: "恢复到当前工作",
    },
    activityLabels: {
      idle: "可响应",
      waiting: "等待中",
      working: "工作中",
      recovering: "恢复中",
      completed: "已完成",
      failed: "需要处理",
      interrupted: "已中断",
    },
    interruptibilityLabels: {
      interruptible: "可直接联系",
      coordinate_first: "请先协调",
      needs_intervention: "需要介入",
    },
  },
  site: {
    name: "Agent Company",
    title: "Agent Company",
    description:
      "Give a goal to a local AI team, keep execution controllable, and receive a verified delivery.",
    tagline: "Local-first AI team",
    author: "Agent Company",
    repo: "https://github.com/Ericwong5021/agents-company",
    deployUrl: "https://github.com/Ericwong5021/agents-company",
    ogImage: "/agent-company-mark.svg",
    twitter: "",
  },
  ui: {
    colors: {
      primary: "neutral",
      neutral: "neutral",
    },
    button: {
      slots: {
        base: "min-h-10 touch-manipulation active:scale-95 transition-transform duration-150 motion-reduce:transform-none",
      },
      defaultVariants: {
        size: "sm",
      },
    },
  },
});
