import type { RuntimeCapabilities, RuntimeID } from "./interface"

export const RuntimeCapabilityMatrix = {
  pi: {
    resume: false,
    interrupt: true,
    liveInput: true,
    structuredEvents: true,
    toolCalls: true,
    structuredOutput: true,
    workspaceRead: true,
    workspaceWrite: true,
    approvals: true,
    reasoningEffort: true,
    subagents: false,
    usageAccounting: true,
    dynamicSkills: true,
    governanceSignals: true,
  },
  "claude-code": {
    resume: true,
    interrupt: true,
    liveInput: false,
    structuredEvents: true,
    toolCalls: true,
    structuredOutput: true,
    workspaceRead: true,
    workspaceWrite: true,
    approvals: true,
    reasoningEffort: false,
    subagents: true,
    usageAccounting: true,
    dynamicSkills: false,
    governanceSignals: false,
  },
  codex: {
    resume: true,
    interrupt: true,
    liveInput: false,
    structuredEvents: true,
    toolCalls: true,
    structuredOutput: true,
    workspaceRead: true,
    workspaceWrite: true,
    approvals: true,
    reasoningEffort: true,
    subagents: true,
    usageAccounting: true,
    dynamicSkills: false,
    governanceSignals: false,
  },
} satisfies Record<RuntimeID, RuntimeCapabilities>
