import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.AGENTCOMPANY_MODELS_URL || "https://models.dev"
const snapshotPath = path.join(dir, "src/provider/models-snapshot.js")
async function trackedModelsData() {
  const source = await Bun.file(snapshotPath).text()
  const marker = "export const snapshot = "
  const index = source.indexOf(marker)
  if (index < 0) throw new Error(`Invalid tracked models snapshot: ${snapshotPath}`)
  return source.slice(index + marker.length).trim()
}

const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`)
      .then((response) => {
        if (!response.ok) throw new Error(`models.dev returned HTTP ${response.status}`)
        return response.text()
      })
      .catch(async (error) => {
        console.warn(`Using tracked models snapshot: ${error instanceof Error ? error.message : String(error)}`)
        return trackedModelsData()
      })
await Bun.write(
  snapshotPath,
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
